# Explore here

In [4]:
import pandas as pd

In [5]:
df = pd.read_csv('/workspaces/Streamlit/data/raw/StudentPerformanceFactors.csv')
df

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,High,Medium,No,7,76,Medium,Yes,1,High,Medium,Public,Positive,2,No,High School,Near,Female,68
6603,23,76,High,Medium,No,8,81,Medium,Yes,3,Low,High,Public,Positive,2,No,High School,Near,Female,69
6604,20,90,Medium,Low,Yes,6,65,Low,Yes,3,Low,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68
6605,10,86,High,High,Yes,6,91,High,Yes,2,Low,Medium,Private,Positive,3,No,High School,Far,Female,68
6606,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,Medium,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 20 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
dtypes: int64(7), object(13)
memory usage: 1.0+ MB

In [7]:
df.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6607.000000,6607.000000,6607.00000,6607.000000,6607.000000,6607.000000,6607.000000
mean,19.975329,79.977448,7.02906,75.070531,1.493719,2.967610,67.235659
std,5.990594,11.547475,1.46812,14.399784,1.230570,1.031231,3.890456
min,1.000000,60.000000,4.00000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.00000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.00000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.00000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.00000,100.000000,8.000000,6.000000,101.000000

In [8]:
df2 = df[df['Exam_Score']<101]
df2.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6606.000000,6606.000000,6606.000000,6606.000000,6606.000000,6606.000000,6606.000000
mean,19.974266,79.974720,7.029216,75.067817,1.493188,2.967605,67.230548
std,5.990424,11.546219,1.468177,14.399184,1.229907,1.031309,3.868502
min,1.000000,60.000000,4.000000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.000000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.000000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.000000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.000000,100.000000,8.000000,6.000000,100.000000

In [11]:
from sklearn.model_selection import train_test_split

X = df2.drop(['Exam_Score'],axis=1)
y = df2['Exam_Score']

X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8,random_state=42)

X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5284 entries, 5937 to 860
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               5284 non-null   int64
 1   Attendance                  5284 non-null   int64
 2   Parental_Involvement        5284 non-null   object
 3   Access_to_Resources         5284 non-null   object
 4   Extracurricular_Activities  5284 non-null   object
 5   Sleep_Hours                 5284 non-null   int64
 6   Previous_Scores             5284 non-null   int64
 7   Motivation_Level            5284 non-null   object
 8   Internet_Access             5284 non-null   object
 9   Tutoring_Sessions           5284 non-null   int64
 10  Family_Income               5284 non-null   object
 11  Teacher_Quality             5222 non-null   object
 12  School_Type                 5284 non-null   object
 13  Peer_Influence              5284 non-null   object
 14  Physical_Activity           5284 non-null   int64
 15  Learning_Disabilities       5284 non-null   object
 16  Parental_Education_Level    5219 non-null   object
 17  Distance_from_Home          5232 non-null   object
 18  Gender                      5284 non-null   object
dtypes: int64(6), object(13)
memory usage: 825.6+ KB

In [18]:
cols = X_train.columns

cols_num = df2._get_numeric_data().columns
cols_num

Index(['Hours_Studied', 'Attendance', 'Sleep_Hours', 'Previous_Scores',
       'Tutoring_Sessions', 'Physical_Activity', 'Exam_Score'],
      dtype='object')

In [19]:
cols_cat = list(set(cols)-set(cols_num))
cols_cat

['Teacher_Quality',
 'Gender',
 'Extracurricular_Activities',
 'Parental_Education_Level',
 'Parental_Involvement',
 'Learning_Disabilities',
 'Peer_Influence',
 'School_Type',
 'Family_Income',
 'Distance_from_Home',
 'Access_to_Resources',
 'Motivation_Level',
 'Internet_Access']

In [23]:
for col in cols_cat:
    df2[col+'_num'] = pd.factorize(df2[col])[0]
df3 = df2.drop(cols_cat,axis=1)
df3

/tmp/ipykernel_2751/746009545.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col+'_num'] = pd.factorize(df2[col])[0]
/tmp/ipykernel_2751/746009545.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col+'_num'] = pd.factorize(df2[col])[0]
/tmp/ipykernel_2751/746009545.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col+'_num'] = pd.factorize(df2[col])[0]
/tmp/ipykernel_2751/746009545.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col+'_num'] = pd.factorize(df2[col])[0]
/tmp/ipykernel_2751/746009545.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col+'_num'] = pd.factorize(df2[col])[0]
/tmp/ipykernel_2751/746009545.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col+'_num'] = pd.factorize(df2[col])[0]
/tmp/ipykernel_2751/746009545.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col+'_num'] = pd.factorize(df2[col])[0]
/tmp/ipykernel_2751/746009545.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col+'_num'] = pd.factorize(df2[col])[0]
/tmp/ipykernel_2751/746009545.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col+'_num'] = pd.factorize(df2[col])[0]
/tmp/ipykernel_2751/746009545.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col+'_num'] = pd.factorize(df2[col])[0]
/tmp/ipykernel_2751/746009545.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col+'_num'] = pd.factorize(df2[col])[0]
/tmp/ipykernel_2751/746009545.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col+'_num'] = pd.factorize(df2[col])[0]
/tmp/ipykernel_2751/746009545.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2[col+'_num'] = pd.factorize(df2[col])[0]

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score,Teacher_Quality_num,Gender_num,Extracurricular_Activities_num,Parental_Education_Level_num,Parental_Involvement_num,Learning_Disabilities_num,Peer_Influence_num,School_Type_num,Family_Income_num,Distance_from_Home_num,Access_to_Resources_num,Motivation_Level_num,Internet_Access_num
0,23,84,7,73,0,3,67,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19,64,8,59,2,4,61,0,1,0,1,0,0,1,0,1,1,1,0,0
2,24,98,7,91,2,4,74,0,0,1,2,1,0,2,0,1,0,1,1,0
3,29,89,8,98,1,4,71,0,0,1,0,0,0,1,0,1,1,1,1,0
4,19,92,6,65,3,4,70,1,1,1,1,1,0,2,0,1,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6602,25,69,7,76,1,2,68,0,1,0,0,2,0,0,0,2,0,1,1,0
6603,23,76,8,81,3,2,69,1,1,0,0,2,0,0,0,0,0,1,1,0
6604,20,90,6,65,3,2,68,0,1,1,2,1,0,1,0,0,0,2,0,0
6605,10,86,6,91,2,3,68,0,1,1,0,2,0,0,1,0,2,0,2,0
6606,15,67,9,94,0,4,64,0,0,1,2,1,0,0,0,1,0,2,1,0

In [32]:
X = df3.drop(['Exam_Score'],axis=1)
y = df3['Exam_Score']

X_train, X_test, y_train, y_test = train_test_split(X,y,train_size=0.8,random_state=42)

X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5284 entries, 5937 to 860
Data columns (total 19 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Hours_Studied                   5284 non-null   int64
 1   Attendance                      5284 non-null   int64
 2   Sleep_Hours                     5284 non-null   int64
 3   Previous_Scores                 5284 non-null   int64
 4   Tutoring_Sessions               5284 non-null   int64
 5   Physical_Activity               5284 non-null   int64
 6   Teacher_Quality_num             5284 non-null   int64
 7   Gender_num                      5284 non-null   int64
 8   Extracurricular_Activities_num  5284 non-null   int64
 9   Parental_Education_Level_num    5284 non-null   int64
 10  Parental_Involvement_num        5284 non-null   int64
 11  Learning_Disabilities_num       5284 non-null   int64
 12  Peer_Influence_num              5284 non-null   int64
 13  School_Type_num                 5284 non-null   int64
 14  Family_Income_num               5284 non-null   int64
 15  Distance_from_Home_num          5284 non-null   int64
 16  Access_to_Resources_num         5284 non-null   int64
 17  Motivation_Level_num            5284 non-null   int64
 18  Internet_Access_num             5284 non-null   int64
dtypes: int64(19)
memory usage: 825.6 KB

In [53]:
X_train.columns

Index(['Hours_Studied', 'Attendance', 'Sleep_Hours', 'Previous_Scores',
       'Tutoring_Sessions', 'Physical_Activity', 'Teacher_Quality_num',
       'Gender_num', 'Extracurricular_Activities_num',
       'Parental_Education_Level_num', 'Parental_Involvement_num',
       'Learning_Disabilities_num', 'Peer_Influence_num', 'School_Type_num',
       'Family_Income_num', 'Distance_from_Home_num',
       'Access_to_Resources_num', 'Motivation_Level_num',
       'Internet_Access_num'],
      dtype='object')

In [33]:
from sklearn.tree import DecisionTreeRegressor

model = DecisionTreeRegressor(random_state=42)

model.fit(X_train,y_train)

DecisionTreeRegressor(random_state=42)

In [34]:
y_pred = model.predict(X_test)
y_pred

array([68., 63., 71., ..., 69., 71., 69.])

In [56]:
X_test.columns

Index(['Hours_Studied', 'Attendance', 'Sleep_Hours', 'Previous_Scores',
       'Tutoring_Sessions', 'Physical_Activity', 'Teacher_Quality_num',
       'Gender_num', 'Extracurricular_Activities_num',
       'Parental_Education_Level_num', 'Parental_Involvement_num',
       'Learning_Disabilities_num', 'Peer_Influence_num', 'School_Type_num',
       'Family_Income_num', 'Distance_from_Home_num',
       'Access_to_Resources_num', 'Motivation_Level_num',
       'Internet_Access_num'],
      dtype='object')

In [35]:
from sklearn.metrics import r2_score, root_mean_squared_error

print (f'R2 Score : {r2_score(y_test,y_pred)}')
print (f'RMSE Score : {root_mean_squared_error(y_test,y_pred)}')

R2 Score : -0.07994217315205288
RMSE Score : 3.7790728797629396

In [37]:
model.feature_names_in_

array(['Hours_Studied', 'Attendance', 'Sleep_Hours', 'Previous_Scores',
       'Tutoring_Sessions', 'Physical_Activity', 'Teacher_Quality_num',
       'Gender_num', 'Extracurricular_Activities_num',
       'Parental_Education_Level_num', 'Parental_Involvement_num',
       'Learning_Disabilities_num', 'Peer_Influence_num',
       'School_Type_num', 'Family_Income_num', 'Distance_from_Home_num',
       'Access_to_Resources_num', 'Motivation_Level_num',
       'Internet_Access_num'], dtype=object)

In [55]:
model.feature_importances_

array([0.23769372, 0.38542325, 0.02161667, 0.07869697, 0.03144794,
       0.03780942, 0.01320216, 0.00149744, 0.00520731, 0.01979112,
       0.04332789, 0.00613859, 0.01166644, 0.01305226, 0.02035152,
       0.01860865, 0.04057176, 0.01169094, 0.00220596])

In [39]:
from sklearn.decomposition import PCA

pca = PCA(n_components=4)
X_train_pca = pca.fit_transform(X_train)
X_test_pca = pca.transform(X_test)

In [40]:
X_train_pca

array([[  2.12863741,  -4.85601101,  -9.04995481,   1.99680064],
       [  3.19980713,  -6.79261419, -12.06203677,   1.03488372],
       [ -6.91310343,  -4.24710218,  -9.98804855,  -2.93164829],
       ...,
       [ -3.88059447,  -3.18347112,   1.99631551,  -1.0835436 ],
       [  8.82567645, -18.62141724,   0.8283072 ,   0.96112579],
       [ -0.20653776, -18.02889908,   0.89595742,  -1.04747676]])

In [41]:
model2 = DecisionTreeRegressor(random_state=42)
model2.fit(X_train_pca,y_train)

y_pred_pca = model2.predict(X_test_pca)

print (f'R2 Score : {r2_score(y_test,y_pred_pca)}')
print (f'RMSE Score : {root_mean_squared_error(y_test,y_pred_pca)}')

R2 Score : 0.08856999009508426
RMSE Score : 3.4717358879446696

In [51]:
print(f'Varianza PCA: {pca.explained_variance_ratio_.sum()}\nExplica {pca.explained_variance_ratio_.sum()*100:.2f}\
 % de la varianza de los datos de todas las columnas anteriores en 4 columnas')

Varianza PCA: 0.9797409478723034
Explica 97.97 % de la varianza de los datos de todas las columnas anteriores en 4 columnas

In [46]:
from pickle import dump

dump(model2,open('../models/decission_tree_classifier_42_pca.sav','wb'))
dump(pca,open('../models/pcs_4.sav','wb'))

In [52]:
X_train.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Teacher_Quality_num,Gender_num,Extracurricular_Activities_num,Parental_Education_Level_num,Parental_Involvement_num,Learning_Disabilities_num,Peer_Influence_num,School_Type_num,Family_Income_num,Distance_from_Home_num,Access_to_Resources_num,Motivation_Level_num,Internet_Access_num
count,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000,5284.000000
mean,20.009084,79.995079,7.022142,75.034254,1.491105,2.973316,0.485238,0.419569,0.595004,0.676949,1.085163,0.109008,0.984671,0.299962,0.794095,0.494322,0.893641,0.906321,0.074754
std,5.967791,11.534293,1.469895,14.364517,1.232762,1.029862,0.688986,0.493535,0.490938,0.795543,0.693617,0.311679,0.888413,0.458284,0.743191,0.684988,0.695055,0.695110,0.263019
min,1.000000,60.000000,4.000000,50.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.000000,0.000000,0.000000,0.000000
25%,16.000000,70.000000,6.000000,63.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,20.000000,80.000000,7.000000,75.000000,1.000000,3.000000,0.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,1.000000,1.000000,0.000000
75%,24.000000,90.000000,8.000000,87.000000,2.000000,4.000000,1.000000,1.000000,1.000000,1.000000,2.000000,0.000000,2.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000
max,44.000000,100.000000,10.000000,100.000000,8.000000,6.000000,2.000000,1.000000,1.000000,2.000000,2.000000,1.000000,2.000000,1.000000,2.000000,2.000000,2.000000,2.000000,1.000000